/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "all.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

volatile unsigned int g_Duty_Cycle=0;//占空比（为百分值）
static unsigned int g_Interrupt_Cycle=100;//中断周期μs最大为2097ms
const unsigned int g_PWM_Steps=100;//PWM周期内总步长
const unsigned char g_Brightness_Table[100] =
	{
	      0,   0,   0,   1,   2,   2,   4,   5,   6,   8,
	     10,  11,  14,  16,  18,  21,  23,  26,  29,  32,
	     35,  38,  41,  44,  47,  50,  53,  56,  59,  62,
	     65,  68,  71,  74,  77,  79,  82,  84,  86,  89,
	     90,  92,  94,  95,  96,  98,  98,  99, 100, 100,
	    100, 100, 100,  99,  98,  98,  96,  95,  94,  92,
	     90,  89,  86,  84,  82,  79,  77,  74,  71,  68,
	     65,  62,  59,  56,  53,  50,  47,  44,  41,  38,
	     35,  32,  29,  26,  23,  21,  18,  16,  14,  11,
	     10,   8,   6,   5,   4,   2,   2,   1,   0,   0,
	};
/**
 * @brief    SysTick以及GPIOC的初始化
 * @param    void
 * @return   void
 * @note     写CVR清计数器并从RVR重载
 * 			 RVR减1：数到0也算一拍
 */

int main(void)
{
	unsigned int i=0;

	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;
	GPIOC->CRH &= GPIOC_CRH_P13_INIT;
	GPIOC->CRH |= GPIOC_CRH_P13_CONFIG;//GPIOC端口13配置为推挽输出2MHZ
	(void)(SysTick->CSR & SysTick_CSR_COUNTFLAG);
	SysTick->RVR = g_Interrupt_Cycle * SYS_CLK_FREQ -1;//晶振频率是8MHz
	SysTick->CVR = 0;//写值清零，值大小无所谓
	SysTick->CSR |= SysTick_CSR_CLKSOURCE | SysTick_CSR_TICKINT | SysTick_CSR_ENABLE;//内核时钟。产生异常。使能。
	while(1)
	{
		if(g_PWM_Circle_Flag==1)
			{
				g_PWM_Circle_Flag=0;
				if(++i>99) i=0;
				g_Duty_Cycle=g_Brightness_Table[i];
			}
	}
}
